name: Git-test
env:
  NEW_NAME: "FirstTest"
  
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "My env is ${{ env.NEW_NAME }}"
    
    - name: Git clone
      uses: actions/checkout@v1
      
    - name: List
      run: ls -al
    - name: Second echo
      run: echo "Hello world"
